### ISSUE TITLE
have plan to release it?

### ISSUE THREAD

**Issue by HaoLiuHust** [kgrm/face-recog-eval#1]

**Comment by changebio** [comment]
Same question

**Comment by kgrm** [comment]
@HaoLiuHust  @changebio thank you for your interest. The model definitions and weights are now available.

**Comment by changebio** [comment]
Thanks a lot

**Comment by changebio** [comment]
Thanks a lot. Where can I find the pre-trained model?

**Comment by kgrm** [comment]
Please see the link in the readme.
